# Generated by Django 3.2.25 on 2024-11-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polybook', '0004_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
